# .github/workflows/crawler.yml
name: New Word Crawler Pipeline

on:
  schedule:
    - cron: '0 18 * * *' # 毎日午前3時 (JST)
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sudachipy SudachiDict-full
          pip install requests beautifulsoup4 pdfplumber python-docx python-pptx supabase

      - name: 4. Run URL Discoverer
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python discover_urls.py

      - name: 5. Run Queue Processor
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python process_queue.py
