# .github/workflows/crawler.yml
name: New Word Crawler Pipeline (Sequential Build)

on:
  schedule:
    # 6時間ごとに実行 (0時, 6時, 12時, 18時 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  # Job 1: サイト内をクロールし、URLを発見する
  discover:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: pip install requests beautifulsoup4 supabase configparser

      - name: 4. Run URL Discoverer
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python discover_urls.py

  # Job 2: 発見されたURLのコンテンツを解析する
  process:
    # discoverジョブの完了を待ってから開始
    needs: discover
    runs-on: ubuntu-latest
    timeout-minutes: 350
    strategy:
      matrix:
        # 解析ジョブのインスタンス数
        instance: [1]
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install all dependencies
        run: |
          pip install sudachipy SudachiDict-full sudachi-tools
          pip install requests beautifulsoup4 supabase configparser
      
      - name: 4. Build User Dictionary Source from Supabase
        id: build_source
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python build_dict_source.py
        
      - name: 5. Compile User Dictionary Binary
        id: compile_dict
        run: |
          # ソースCSVが存在し、中身が空でない場合のみビルドを実行
          if [ -s user_dict_source.csv ]; then
            echo "CSV source found. Compiling user dictionary..."
            sudachipy ubuild -o user.dict user_dict_source.csv
            echo "USER_DICT_PATH=user.dict" >> $GITHUB_ENV
          else
            echo "User dictionary source is empty. Skipping build."
            echo "USER_DICT_PATH=" >> $GITHUB_ENV
          fi

      - name: 6. Run Queue Processor
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          # 前のステップで生成した辞書のパスを環境変数で渡す
          USER_DICT_PATH: ${{ env.USER_DICT_PATH }}
        run: python process_queue.py
