# .github/workflows/crawler.yml

# ワークフローの名前
name: New Word Crawler

# ワークフローを実行するトリガー
on:
  schedule:
    # 毎日午前3時 (JST) に実行 (UTCでは18:00)
    - cron: '0 18 * * *'
  # GitHub上で手動実行も可能にする
  workflow_dispatch:

# 実行されるジョブを定義
jobs:
  # 'crawl'という名前のジョブ
  crawl:
    # Ubuntuの最新版で実行
    runs-on: ubuntu-latest

    # ジョブのステップ
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      # 2. Python 3.10 をセットアップ
      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Pythonの依存関係とSudachiの辞書をインストール
      - name: 3. Install Python dependencies and Sudachi Dictionary
        run: |
          python -m pip install --upgrade pip
          pip install sudachipy SudachiDict-full
          pip install requests beautifulsoup4 pdfplumber python-docx python-pptx supabase

      # 4. クローラーのPythonスクリプトを実行
      - name: 4. Run Crawler Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python crawler.py
