# .github/workflows/crawler.yml
name: New Word Crawler Pipeline (Sequential Build)

on:
  schedule:
    # 6時間ごとに実行 (0時, 6時, 12時, 18時 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4
      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 3. Install dependencies
        run: pip install requests beautifulsoup4 supabase configparser
      - name: 4. Run URL Discoverer
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python discover_urls.py

  process:
    needs: discover
    runs-on: ubuntu-latest
    timeout-minutes: 350
    strategy:
      matrix:
        instance: [1]
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4
      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 3. Install all dependencies
        run: |
          # SudachiDict-full をpipでインストール
          pip install sudachipy SudachiDict-full
          pip install requests beautifulsoup4 supabase configparser
      
      - name: 4. Build User Dictionary Source from Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python build_dict_source.py
        
      # ▼▼▼▼▼ このステップを修正 ▼▼▼▼▼
      - name: 5. Compile User Dictionary Binary
        run: |
          # ステップ5-1: pipでインストールされたsystem_full.dicのフルパスをPythonを使って取得
          SYSTEM_DICT_PATH=$(python -c "import sudachidict_full, os; print(os.path.join(os.path.dirname(sudachidict_full.__file__), 'resources', 'system_full.dic'))")
          echo "Found system dictionary at: ${SYSTEM_DICT_PATH}"

          # ステップ5-2: 取得したパスを-sオプションでubuildに渡す
          if [ -s user_dict_source.csv ]; then
            echo "CSV source found. Compiling user dictionary..."
            sudachipy ubuild -s "${SYSTEM_DICT_PATH}" -o user.dict user_dict_source.csv
            echo "USER_DICT_PATH=user.dict" >> $GITHUB_ENV
          else
            echo "User dictionary source is empty. Skipping build."
            echo "USER_DICT_PATH=" >> $GITHUB_ENV
          fi
      # ▲▲▲▲▲ ここまで修正 ▲▲▲▲▲

      - name: 6. Run Queue Processor
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          USER_DICT_PATH: ${{ env.USER_DICT_PATH }}
        run: python process_queue.py
